# Generated by Django 5.1.6 on 2025-03-08 03:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='media/')),
                ('course_publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('course_type', models.CharField(choices=[('JS', 'Javascript'), ('PY', 'Python'), ('CPP', 'C++'), ('C#', 'C Sharp'), ('Java', 'Java'), ('DB', 'Database')], max_length=4)),
                ('course_description', models.TextField()),
            ],
        ),
    ]
