# Generated by Django 5.1.6 on 2025-03-08 14:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_Name', models.CharField(max_length=30)),
                ('thumbnails', models.ImageField(upload_to='media/')),
                ('course_publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Language_Required', models.CharField(choices=[('JS', 'Javascript'), ('PY', 'Python'), ('CPP', 'C++'), ('C#', 'C Sharp'), ('Java', 'Java'), ('DB', 'Database')], max_length=4)),
                ('Course_Description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='courseType',
        ),
    ]
