# Generated by Django 5.1.6 on 2025-03-11 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_course_delete_coursetype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_publish_date',
            new_name='course_Publish_Date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='Course_Description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='Language_Required',
        ),
        migrations.AddField(
            model_name='course',
            name='course_Price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Product Price'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_Description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='language_Required',
            field=models.CharField(choices=[('JS', 'Javascript'), ('PY', 'Python'), ('CPP', 'C++'), ('C#', 'C Sharp'), ('Java', 'Java'), ('DB', 'Database')], default='JS', max_length=4),
        ),
    ]
