# Generated by Django 5.1.6 on 2025-03-11 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_rename_course_publish_date_course_course_publish_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='language_Required',
            field=models.CharField(choices=[('JS', 'Javascript'), ('PY', 'Python'), ('CPP', 'C++'), ('C#', 'C Sharp'), ('Java', 'Java'), ('DB', 'Database')], default=' ', max_length=4),
        ),
    ]
