# Generated by Django 5.1.6 on 2025-03-11 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_alter_course_language_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_Price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Product Price'),
        ),
        migrations.AlterField(
            model_name='course',
            name='language_Required',
            field=models.CharField(choices=[('JS', 'Javascript'), ('PY', 'Python'), ('CPP', 'C++'), ('C#', 'C Sharp'), ('Java', 'Java'), ('DB', 'Database')], default='', max_length=4),
        ),
    ]
