# Generated by Django 5.1.6 on 2025-03-11 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_alter_course_course_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_Price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Product Price'),
        ),
    ]
